/*
 * SwipeFit dataset: muscle groups, avoid-conditions, and the exercise library.
 *
 * Contract (see CLAUDE.md):
 * - The filter UI is generated from CONDITIONS and MUSCLE_GROUPS — never hardcode them in app.js.
 * - Every exercise's `avoidIf` entries must exactly match a CONDITIONS id.
 * - Every `muscleGroup` / `secondaryMuscles` entry must exactly match a MUSCLE_GROUPS name.
 * - Exercise `id`s are permanent — user data references them, so never rename or reuse one.
 * - Run `node validate.js` after any edit to this file.
 *
 * Tagging philosophy: conservative. If a movement commonly aggravates a condition,
 * it's tagged, even though many people with that condition could do it. The user is
 * choosing what to rule out — err on the side of over-tagging.
 */

const MUSCLE_GROUPS = [
  { name: "Chest", color: "#e5484d" },
  { name: "Back", color: "#3e7bfa" },
  { name: "Shoulders", color: "#f59e0b" },
  { name: "Biceps", color: "#8e6bef" },
  { name: "Triceps", color: "#e64ba1" },
  { name: "Core/Abs", color: "#12a594" },
  { name: "Glutes", color: "#f76b15" },
  { name: "Quads", color: "#0ea5e9" },
  { name: "Hamstrings", color: "#7cb314" },
  { name: "Calves", color: "#00a2c7" },
  { name: "Full Body/Cardio", color: "#6e56cf" },
];

const CONDITIONS = [
  { id: "lower-back", label: "Lower Back Issues" },
  { id: "knee", label: "Knee Issues" },
  { id: "shoulder", label: "Shoulder Issues" },
  { id: "wrist", label: "Wrist Issues" },
  { id: "neck", label: "Neck Issues" },
  { id: "hip", label: "Hip Issues" },
  { id: "high-impact", label: "High Impact / Jumping" },
  { id: "balance", label: "Balance Issues" },
  { id: "pregnancy", label: "Pregnancy" },
];

const EXERCISES = [
  // ─────────────────────────── CHEST ───────────────────────────
  {
    id: "pushup-standard",
    name: "Standard Push-Up",
    muscleGroup: "Chest",
    secondaryMuscles: ["Triceps", "Shoulders", "Core/Abs"],
    equipment: "Bodyweight",
    difficulty: "Beginner",
    cue: "Keep your body in a straight line, lower chest to just above the floor.",
    description: "Start in a high plank with hands slightly wider than shoulders. Lower your whole body as one unit until your chest nearly touches the floor, then press back up. Common mistakes: sagging hips, flaring elbows straight out to the sides, and cutting the range short.",
    avoidIf: ["wrist", "shoulder"],
    icon: "💪",
  },
  {
    id: "pushup-incline",
    name: "Incline Push-Up",
    muscleGroup: "Chest",
    secondaryMuscles: ["Triceps", "Shoulders"],
    equipment: "Bodyweight",
    difficulty: "Beginner",
    cue: "Hands on a bench or counter — the higher the surface, the easier the rep.",
    description: "A push-up with your hands elevated on a sturdy bench, box, or countertop. The incline takes weight off your arms and wrists, making it the friendliest push-up variation. Keep the same rigid plank line as a floor push-up; don't let the hips pike up.",
    avoidIf: ["wrist"],
    icon: "💪",
  },
  {
    id: "pushup-knee",
    name: "Knee Push-Up",
    muscleGroup: "Chest",
    secondaryMuscles: ["Triceps", "Shoulders"],
    equipment: "Bodyweight",
    difficulty: "Beginner",
    cue: "Body straight from knees to head — don't hinge at the hips.",
    description: "A push-up performed from the knees to reduce the load. Cross your ankles, squeeze your glutes, and keep a straight line from knees to shoulders while you lower and press. Put a mat or towel under the kneecaps. The most common mistake is bending at the hips so only the arms move.",
    avoidIf: ["wrist", "knee"],
    icon: "💪",
  },
  {
    id: "db-bench-press",
    name: "Dumbbell Bench Press",
    muscleGroup: "Chest",
    secondaryMuscles: ["Triceps", "Shoulders"],
    equipment: "Dumbbell",
    difficulty: "Beginner",
    cue: "Lower the dumbbells to chest level with elbows about 45° from your body.",
    description: "Lie on a flat bench with a dumbbell in each hand at chest level. Press both up until your arms are straight over your chest, then lower with control. Dumbbells let each shoulder find its own comfortable path. Don't bounce the weights off your chest or let your wrists bend backward.",
    avoidIf: ["shoulder"],
    icon: "🏋️",
  },
  {
    id: "db-incline-press",
    name: "Incline Dumbbell Press",
    muscleGroup: "Chest",
    secondaryMuscles: ["Shoulders", "Triceps"],
    equipment: "Dumbbell",
    difficulty: "Intermediate",
    cue: "Set the bench to about 30° — steeper turns it into a shoulder press.",
    description: "A dumbbell press on a bench inclined to roughly 30 degrees, shifting emphasis to the upper chest. Press up and slightly back over your collarbones, and lower until you feel a comfortable stretch. Keep your feet planted and lower back lightly braced, not arched hard.",
    avoidIf: ["shoulder"],
    icon: "🏋️",
  },
  {
    id: "db-chest-fly",
    name: "Dumbbell Chest Fly",
    muscleGroup: "Chest",
    secondaryMuscles: ["Shoulders"],
    equipment: "Dumbbell",
    difficulty: "Intermediate",
    cue: "Arms open like hugging a barrel — elbows stay slightly bent the whole rep.",
    description: "Lying on a bench, open your arms out wide with a soft elbow bend until you feel a stretch across the chest, then squeeze the dumbbells back together above you. Go lighter than you think — the stretched position is where injuries happen. Never let the weights drop below shoulder line if anything pinches.",
    avoidIf: ["shoulder"],
    icon: "🏋️",
  },
  {
    id: "bb-bench-press",
    name: "Barbell Bench Press",
    muscleGroup: "Chest",
    secondaryMuscles: ["Triceps", "Shoulders"],
    equipment: "Barbell",
    difficulty: "Intermediate",
    cue: "Bar touches mid-chest; wrists stacked straight over elbows.",
    description: "The classic barbell press from a flat bench. Grip a bit wider than shoulders, pull your shoulder blades together against the bench, lower the bar to your mid-chest, and press it back over your shoulders. Use a spotter or safety pins when going heavy, and keep your wrists straight rather than folded back.",
    avoidIf: ["shoulder", "wrist"],
    icon: "🏋️",
  },
  {
    id: "machine-chest-press",
    name: "Machine Chest Press",
    muscleGroup: "Chest",
    secondaryMuscles: ["Triceps", "Shoulders"],
    equipment: "Machine",
    difficulty: "Beginner",
    cue: "Adjust the seat so the handles line up with mid-chest.",
    description: "A guided pressing machine — the fixed path makes it one of the easiest ways to load the chest safely. Set the seat so the handles sit at chest height, press to nearly straight arms, and return with control. Don't let the weight stack slam down between reps.",
    avoidIf: ["shoulder"],
    icon: "🏋️",
  },
  {
    id: "band-chest-press",
    name: "Standing Band Chest Press",
    muscleGroup: "Chest",
    secondaryMuscles: ["Triceps", "Core/Abs"],
    equipment: "Band",
    difficulty: "Beginner",
    cue: "Anchor the band behind you at chest height and press straight forward.",
    description: "Anchor a resistance band behind you (door anchor or post), hold a handle in each hand at chest height, and press forward until your arms are straight. A gentle, joint-friendly press you can do anywhere — the band is lightest in the stretched shoulder position, which most people find comfortable. Stagger your stance for balance.",
    avoidIf: [],
    icon: "💪",
  },

  // ─────────────────────────── BACK ───────────────────────────
  {
    id: "band-row",
    name: "Seated Band Row",
    muscleGroup: "Back",
    secondaryMuscles: ["Biceps", "Shoulders"],
    equipment: "Band",
    difficulty: "Beginner",
    cue: "Pull the band to your ribs and squeeze your shoulder blades together.",
    description: "Sit tall on the floor with legs extended, loop a band around your feet, and row the handles to your lower ribs. Lead with the elbows and finish each rep by pinching the shoulder blades. A very forgiving introduction to rowing — keep the torso upright rather than rocking back and forth for momentum.",
    avoidIf: [],
    icon: "🚣",
  },
  {
    id: "db-single-row",
    name: "One-Arm Dumbbell Row",
    muscleGroup: "Back",
    secondaryMuscles: ["Biceps", "Shoulders"],
    equipment: "Dumbbell",
    difficulty: "Beginner",
    cue: "Brace one hand on a bench; pull the dumbbell to your hip, not your armpit.",
    description: "With one hand and one knee supported on a bench, row a dumbbell from a dead hang up to your hip pocket. The bench support makes it much easier on the lower back than bent-over barbell work, but your spine still needs to stay long and neutral — no twisting to heave the weight up.",
    avoidIf: ["lower-back"],
    icon: "🚣",
  },
  {
    id: "bb-bent-row",
    name: "Bent-Over Barbell Row",
    muscleGroup: "Back",
    secondaryMuscles: ["Biceps", "Hamstrings", "Core/Abs"],
    equipment: "Barbell",
    difficulty: "Advanced",
    cue: "Hinge to ~45°, flat back, and pull the bar to your lower ribs.",
    description: "Hinge at the hips with a barbell hanging at arm's length, then row it to your lower ribcage while holding the hinge position dead still. Brutal and effective, but it demands an iron flat back — the moment your spine rounds or you jerk the weight with your hips, back off the load.",
    avoidIf: ["lower-back"],
    icon: "🏋️",
  },
  {
    id: "lat-pulldown",
    name: "Lat Pulldown",
    muscleGroup: "Back",
    secondaryMuscles: ["Biceps", "Shoulders"],
    equipment: "Cable",
    difficulty: "Beginner",
    cue: "Pull the bar to your collarbones; chest up, no leaning way back.",
    description: "Seated at a pulldown station, grip the bar a bit wider than your shoulders and pull it down to the top of your chest, then let it rise with control until your arms are long. Think 'elbows into your back pockets'. Don't pull behind the neck, and don't turn it into a lie-back rowing motion.",
    avoidIf: ["shoulder"],
    icon: "🧗",
  },
  {
    id: "pullup",
    name: "Pull-Up",
    muscleGroup: "Back",
    secondaryMuscles: ["Biceps", "Core/Abs", "Shoulders"],
    equipment: "Bodyweight",
    difficulty: "Advanced",
    cue: "Start from a dead hang; pull until your chin clears the bar.",
    description: "Hang from a bar with an overhand grip just wider than your shoulders, and pull until your chin passes the bar. Lower all the way back to straight arms each rep. If a full rep isn't there yet, use band assistance or slow negatives. Avoid kipping or swinging unless you've specifically trained it.",
    avoidIf: ["shoulder"],
    icon: "🧗",
  },
  {
    id: "chinup",
    name: "Chin-Up",
    muscleGroup: "Back",
    secondaryMuscles: ["Biceps", "Core/Abs"],
    equipment: "Bodyweight",
    difficulty: "Advanced",
    cue: "Underhand grip, shoulder-width — pull your chest toward the bar.",
    description: "A pull-up with palms facing you, which brings the biceps in strongly and most people find slightly easier. Dead hang to chin-over-bar, no half reps at the top and no dropping like a stone at the bottom. Grip shoulder-width; going too narrow can grumble at elbows and wrists.",
    avoidIf: ["shoulder"],
    icon: "🧗",
  },
  {
    id: "seated-cable-row",
    name: "Seated Cable Row",
    muscleGroup: "Back",
    secondaryMuscles: ["Biceps", "Shoulders"],
    equipment: "Cable",
    difficulty: "Beginner",
    cue: "Sit tall, pull the handle to your stomach, and don't rock your torso.",
    description: "Seated at a low cable with feet braced, pull the handle to your belly while keeping your torso vertical, then let your arms and shoulder blades reach forward under control. The temptation is to swing your body for extra weight — resist it and let the back do the work.",
    avoidIf: ["lower-back"],
    icon: "🚣",
  },
  {
    id: "superman",
    name: "Superman Hold",
    muscleGroup: "Back",
    secondaryMuscles: ["Glutes", "Hamstrings"],
    equipment: "Bodyweight",
    difficulty: "Beginner",
    cue: "Lift arms and legs a few inches off the floor and hold — no straining the neck.",
    description: "Lie face-down, arms extended overhead, and lift your arms, chest, and legs slightly off the floor by squeezing your back and glutes. Hold for a few seconds and lower. Lift to a comfortable height, not as high as possible — this is a gentle endurance move for the spinal muscles, not a max-effort arch.",
    avoidIf: ["lower-back", "pregnancy"],
    icon: "🦸",
  },
  {
    id: "inverted-row",
    name: "Inverted Row",
    muscleGroup: "Back",
    secondaryMuscles: ["Biceps", "Core/Abs"],
    equipment: "Bodyweight",
    difficulty: "Intermediate",
    cue: "Hang under a sturdy bar or table edge; pull your chest to it, body rigid.",
    description: "Set a bar around waist height (or use a sturdy table edge), hang underneath with heels on the floor, and row your chest up to the bar while your body stays plank-straight. Walk your feet closer to make it easier, further to make it harder. A great pull-up builder that scales to any level.",
    avoidIf: ["shoulder"],
    icon: "🚣",
  },
  {
    id: "renegade-row",
    name: "Renegade Row",
    muscleGroup: "Back",
    secondaryMuscles: ["Core/Abs", "Shoulders", "Triceps"],
    equipment: "Dumbbell",
    difficulty: "Advanced",
    cue: "Row from a plank on two dumbbells without letting your hips twist.",
    description: "In a push-up position with each hand on a dumbbell, row one weight to your hip while the rest of you fights to stay perfectly square to the floor. Feet wide for stability. It's as much an anti-rotation core drill as a row — if your hips are swinging, the weight is too heavy.",
    avoidIf: ["wrist", "lower-back", "balance"],
    icon: "🚣",
  },

  // ───────────────────────── SHOULDERS ─────────────────────────
  {
    id: "db-shoulder-press",
    name: "Seated Dumbbell Shoulder Press",
    muscleGroup: "Shoulders",
    secondaryMuscles: ["Triceps"],
    equipment: "Dumbbell",
    difficulty: "Beginner",
    cue: "Press from ear level to straight arms overhead — don't shrug into your neck.",
    description: "Seated with back support, hold a dumbbell at each side of your head and press both overhead until your arms are straight, then lower to about ear level. Keep your ribs down and lower back against the pad rather than arching to finish the press. Lower the seat-back a notch if a strict vertical press pinches.",
    avoidIf: ["shoulder", "neck"],
    icon: "🏋️",
  },
  {
    id: "bb-overhead-press",
    name: "Barbell Overhead Press",
    muscleGroup: "Shoulders",
    secondaryMuscles: ["Triceps", "Core/Abs"],
    equipment: "Barbell",
    difficulty: "Intermediate",
    cue: "Squeeze glutes, brace abs, press the bar to lockout and bring your head through.",
    description: "Standing with the bar at your collarbones, brace your whole body and press it overhead until your arms lock out with the bar over the middle of your foot. The strict standing press builds serious shoulders but transmits load through the whole spine — any layback turns it into a lower-back exercise, which is not the goal.",
    avoidIf: ["shoulder", "neck", "lower-back"],
    icon: "🏋️",
  },
  {
    id: "db-lateral-raise",
    name: "Dumbbell Lateral Raise",
    muscleGroup: "Shoulders",
    secondaryMuscles: [],
    equipment: "Dumbbell",
    difficulty: "Beginner",
    cue: "Raise the weights out to shoulder height, pinky slightly up, and lower slowly.",
    description: "Standing with light dumbbells at your sides, raise your arms out until they're parallel with the floor, then lower with control. Slight elbow bend, no swinging. These stay light forever — form collapses fast when people chase weight, and above-shoulder height adds risk without benefit.",
    avoidIf: ["shoulder"],
    icon: "💪",
  },
  {
    id: "db-front-raise",
    name: "Dumbbell Front Raise",
    muscleGroup: "Shoulders",
    secondaryMuscles: [],
    equipment: "Dumbbell",
    difficulty: "Beginner",
    cue: "Lift straight in front to eye level, one controlled rep at a time.",
    description: "Raise a dumbbell (or one in each hand) straight out in front of you to about eye level, then lower slowly. Keep a soft elbow and avoid rocking your torso backward to heave the weight — if you need momentum, it's too heavy. Alternating arms helps keep the reps honest.",
    avoidIf: ["shoulder"],
    icon: "💪",
  },
  {
    id: "rear-delt-fly",
    name: "Bent-Over Rear Delt Fly",
    muscleGroup: "Shoulders",
    secondaryMuscles: ["Back"],
    equipment: "Dumbbell",
    difficulty: "Intermediate",
    cue: "Hinge forward, then open your arms out like wings — light weight, high control.",
    description: "Hinge at the hips until your torso is near-parallel to the floor and raise light dumbbells out to your sides, leading with the elbows. Targets the often-neglected back of the shoulder. Sit your chest on an incline bench if holding the hinge bothers your lower back.",
    avoidIf: ["shoulder", "lower-back"],
    icon: "💪",
  },
  {
    id: "band-pull-apart",
    name: "Band Pull-Apart",
    muscleGroup: "Shoulders",
    secondaryMuscles: ["Back"],
    equipment: "Band",
    difficulty: "Beginner",
    cue: "Arms straight at chest height — pull the band apart until it touches your chest.",
    description: "Hold a light band in front of you with straight arms and pull it apart until your arms form a T and the band touches your chest, then return slowly. A gentle staple for posture and shoulder health that most people can do daily. Keep the shoulders down away from the ears.",
    avoidIf: [],
    icon: "💪",
  },
  {
    id: "arnold-press",
    name: "Arnold Press",
    muscleGroup: "Shoulders",
    secondaryMuscles: ["Triceps"],
    equipment: "Dumbbell",
    difficulty: "Advanced",
    cue: "Start palms facing you, rotate out as you press overhead.",
    description: "Begin with dumbbells at shoulder height, palms facing you, then rotate your palms outward as you press overhead, finishing like a normal shoulder press. The added rotation sweeps through more of the shoulder but also demands more from it — keep the weight moderate and the tempo smooth.",
    avoidIf: ["shoulder", "neck"],
    icon: "🏋️",
  },
  {
    id: "face-pull",
    name: "Cable Face Pull",
    muscleGroup: "Shoulders",
    secondaryMuscles: ["Back"],
    equipment: "Cable",
    difficulty: "Intermediate",
    cue: "Pull the rope toward your eyes, elbows high, thumbs pointing behind you.",
    description: "Set a rope attachment at face height, pull it toward your eyes while spreading the rope ends apart, and finish with your upper arms in a 'double biceps' position. One of the best movements for shoulder balance and posture. Light weight and a deliberate squeeze beat heavy yanking every time.",
    avoidIf: [],
    icon: "🎯",
  },
  {
    id: "db-shrug",
    name: "Dumbbell Shrug",
    muscleGroup: "Shoulders",
    secondaryMuscles: ["Back"],
    equipment: "Dumbbell",
    difficulty: "Beginner",
    cue: "Straight up toward your ears, pause, straight down — no rolling.",
    description: "Stand holding dumbbells at your sides and lift your shoulders straight up toward your ears, pause, and lower. That's the whole move — rolling the shoulders in circles under load adds nothing and irritates necks. Works the upper traps, which take a lot of daily desk-posture abuse.",
    avoidIf: ["neck"],
    icon: "🤷",
  },
  {
    id: "upright-row",
    name: "Barbell Upright Row",
    muscleGroup: "Shoulders",
    secondaryMuscles: ["Back", "Biceps"],
    equipment: "Barbell",
    difficulty: "Advanced",
    cue: "Pull the bar up your body to chest height, elbows leading — and no higher.",
    description: "Holding a barbell in front of your thighs, pull it up along your body to about chest height with your elbows leading the way. Stop at chest height: pulling to the chin with a narrow grip is the classic recipe for shoulder impingement. A wider grip and moderate height keep it productive; skip it entirely if your shoulders complain.",
    avoidIf: ["shoulder", "wrist", "neck"],
    icon: "🏋️",
  },

  // ─────────────────────────── BICEPS ───────────────────────────
  {
    id: "db-curl",
    name: "Dumbbell Biceps Curl",
    muscleGroup: "Biceps",
    secondaryMuscles: [],
    equipment: "Dumbbell",
    difficulty: "Beginner",
    cue: "Elbows pinned to your sides; curl up, lower for a slow three-count.",
    description: "Stand or sit with a dumbbell in each hand, palms forward, and curl the weights to your shoulders without letting your elbows drift forward or your torso swing. The lowering half is where the growth is — take it slow. Swap to alternating arms if both-at-once invites cheating.",
    avoidIf: [],
    icon: "💪",
  },
  {
    id: "hammer-curl",
    name: "Hammer Curl",
    muscleGroup: "Biceps",
    secondaryMuscles: [],
    equipment: "Dumbbell",
    difficulty: "Beginner",
    cue: "Palms facing each other the whole rep, like swinging a hammer.",
    description: "A curl with a neutral grip — palms facing your body throughout. Hits the brachialis and forearms along with the biceps, and the neutral wrist position is the most comfortable curl grip for most people. Same rules as any curl: elbows glued to your ribs, no swinging.",
    avoidIf: [],
    icon: "💪",
  },
  {
    id: "bb-curl",
    name: "Barbell Curl",
    muscleGroup: "Biceps",
    secondaryMuscles: [],
    equipment: "Barbell",
    difficulty: "Intermediate",
    cue: "Shoulder-width grip; curl the bar without leaning back.",
    description: "The heaviest-loading curl. Grip a barbell at shoulder width and curl it to your collarbones, keeping your elbows at your sides and your torso tall. The straight bar locks your wrists into full rotation, which some wrists resent — an EZ-curl bar or dumbbells are drop-in replacements if it nags.",
    avoidIf: ["wrist"],
    icon: "🏋️",
  },
  {
    id: "concentration-curl",
    name: "Concentration Curl",
    muscleGroup: "Biceps",
    secondaryMuscles: [],
    equipment: "Dumbbell",
    difficulty: "Beginner",
    cue: "Elbow braced against your inner thigh — nothing moves but the forearm.",
    description: "Seated, lean forward and brace your elbow against your inner thigh, then curl a single dumbbell with total strictness. The bracing removes every possible cheat, so the weight will be humbling. Squeeze hard at the top and lower until the arm is fully straight.",
    avoidIf: [],
    icon: "💪",
  },
  {
    id: "incline-db-curl",
    name: "Incline Dumbbell Curl",
    muscleGroup: "Biceps",
    secondaryMuscles: [],
    equipment: "Dumbbell",
    difficulty: "Intermediate",
    cue: "Lie back on an incline bench and let your arms hang behind your body line.",
    description: "Curling while lying back on a 45–60° incline bench puts the biceps under stretch at the bottom, which is uncomfortable in the best way. Let the arms hang fully, curl without letting the elbows swing forward. The stretched shoulder position is the trade-off — skip if it feels tweaky at the front of the shoulder.",
    avoidIf: ["shoulder"],
    icon: "💪",
  },
  {
    id: "band-curl",
    name: "Band Biceps Curl",
    muscleGroup: "Biceps",
    secondaryMuscles: [],
    equipment: "Band",
    difficulty: "Beginner",
    cue: "Stand on the band, curl the handles — resistance builds toward the top.",
    description: "Stand on the middle of a resistance band and curl the handles to your shoulders. The band pulls hardest at the top where you're strongest, so it's very joint-friendly at the bottom. Adjust difficulty instantly by widening your stance. Great travel and warm-up option.",
    avoidIf: [],
    icon: "💪",
  },
  {
    id: "cable-curl",
    name: "Cable Biceps Curl",
    muscleGroup: "Biceps",
    secondaryMuscles: [],
    equipment: "Cable",
    difficulty: "Beginner",
    cue: "Constant tension — the cable never lets the biceps rest at the bottom.",
    description: "Curl a handle or bar attached to a low cable pulley. Unlike free weights, the cable keeps tension on the muscle through the entire arc, including at the bottom. Stand a half-step back from the pulley, keep elbows at your sides, and resist the pull on the way down.",
    avoidIf: [],
    icon: "💪",
  },
  {
    id: "preacher-curl",
    name: "Preacher Curl",
    muscleGroup: "Biceps",
    secondaryMuscles: [],
    equipment: "Machine",
    difficulty: "Intermediate",
    cue: "Arms fully on the pad; stop just short of straight at the bottom.",
    description: "Curling with your upper arms fixed on a preacher pad makes cheating impossible and stretches the biceps hard at the bottom. That stretched position under load is also where people strain things — lower under control and stop just before your elbows fully lock. Go lighter than your standing curl.",
    avoidIf: ["wrist"],
    icon: "💪",
  },

  // ─────────────────────────── TRICEPS ───────────────────────────
  {
    id: "bench-dip",
    name: "Bench Dip",
    muscleGroup: "Triceps",
    secondaryMuscles: ["Chest", "Shoulders"],
    equipment: "Bodyweight",
    difficulty: "Intermediate",
    cue: "Hands on the bench behind you; lower until elbows hit 90°, no deeper.",
    description: "With your hands on a bench edge behind you and legs extended in front, bend your elbows to lower your hips toward the floor, then press back up. Keep your back grazing the bench. Going too deep puts the shoulder in an aggressive position — 90° at the elbow is plenty. Bend your knees to make it easier.",
    avoidIf: ["shoulder", "wrist"],
    icon: "🪑",
  },
  {
    id: "overhead-db-extension",
    name: "Overhead Dumbbell Triceps Extension",
    muscleGroup: "Triceps",
    secondaryMuscles: ["Shoulders"],
    equipment: "Dumbbell",
    difficulty: "Intermediate",
    cue: "Both hands under one dumbbell overhead; lower it behind your head, elbows in.",
    description: "Hold one dumbbell overhead with both hands cupped under the top plate, then bend only at the elbows to lower it behind your head and press back up. The long overhead stretch is what makes it effective. Keep your elbows pointing forward, not flaring wide, and your ribs stacked rather than arching.",
    avoidIf: ["shoulder", "neck"],
    icon: "🏋️",
  },
  {
    id: "cable-pushdown",
    name: "Cable Triceps Pushdown",
    muscleGroup: "Triceps",
    secondaryMuscles: [],
    equipment: "Cable",
    difficulty: "Beginner",
    cue: "Elbows pinned; push the handle down until your arms are dead straight.",
    description: "Facing a high cable with a bar or rope attachment, pin your elbows to your sides and straighten your arms fully, then let the handle rise until your forearms pass parallel. The most shoulder-friendly triceps builder there is. Don't lean your whole body onto the handle to move bigger stacks.",
    avoidIf: [],
    icon: "💪",
  },
  {
    id: "skull-crusher",
    name: "Skull Crusher",
    muscleGroup: "Triceps",
    secondaryMuscles: [],
    equipment: "Barbell",
    difficulty: "Intermediate",
    cue: "Lower the bar to your forehead — or just behind it — elbows pointing at the ceiling.",
    description: "Lying on a bench with a barbell or EZ bar held over your chest, bend at the elbows to lower it toward your forehead, then extend back up. Lowering slightly behind the head is easier on the elbows. The name is a warning: control matters, and an EZ bar spares the wrists a straight bar can annoy.",
    avoidIf: ["wrist"],
    icon: "💀",
  },
  {
    id: "diamond-pushup",
    name: "Diamond Push-Up",
    muscleGroup: "Triceps",
    secondaryMuscles: ["Chest", "Shoulders", "Core/Abs"],
    equipment: "Bodyweight",
    difficulty: "Advanced",
    cue: "Thumbs and index fingers form a diamond under your chest.",
    description: "A push-up with your hands close together under your chest, thumbs and index fingers touching in a diamond shape. Shifts the work heavily onto the triceps and is significantly harder than a standard push-up. The narrow hand position cranks on the wrists — elevate the hands or widen slightly if they protest.",
    avoidIf: ["wrist", "shoulder"],
    icon: "💎",
  },
  {
    id: "band-triceps-extension",
    name: "Band Triceps Extension",
    muscleGroup: "Triceps",
    secondaryMuscles: [],
    equipment: "Band",
    difficulty: "Beginner",
    cue: "Anchor the band high, elbows at your sides, straighten your arms.",
    description: "Anchor a band overhead (door anchor or pull-up bar), face it, and press the band down until your arms are straight — a pushdown without the cable stack. Smooth resistance and nearly impossible to do wrong. Step further from the anchor for more tension.",
    avoidIf: [],
    icon: "💪",
  },
  {
    id: "db-kickback",
    name: "Dumbbell Triceps Kickback",
    muscleGroup: "Triceps",
    secondaryMuscles: [],
    equipment: "Dumbbell",
    difficulty: "Beginner",
    cue: "Hinge forward, upper arm parallel to the floor, straighten the elbow fully.",
    description: "Hinge forward with a flat back (or brace one hand on a bench), raise your upper arm parallel to the floor, and extend the dumbbell back until your arm is completely straight. All the value is in the last few degrees and the squeeze at lockout — light weight, full extension, no swinging.",
    avoidIf: ["lower-back"],
    icon: "💪",
  },
  {
    id: "close-grip-bench",
    name: "Close-Grip Bench Press",
    muscleGroup: "Triceps",
    secondaryMuscles: ["Chest", "Shoulders"],
    equipment: "Barbell",
    difficulty: "Intermediate",
    cue: "Hands shoulder-width, elbows tucked along your ribs as the bar comes down.",
    description: "A bench press with your hands at shoulder width and elbows tracking close to your body, shifting the emphasis from chest to triceps. Touch lower on the chest than a regular bench press. Don't go narrower than shoulder width — it doesn't work the triceps harder, it just grinds the wrists.",
    avoidIf: ["shoulder", "wrist"],
    icon: "🏋️",
  },

  // ─────────────────────────── CORE/ABS ───────────────────────────
  {
    id: "plank",
    name: "Plank",
    muscleGroup: "Core/Abs",
    secondaryMuscles: ["Shoulders", "Glutes"],
    equipment: "Bodyweight",
    difficulty: "Beginner",
    cue: "Forearms down, glutes squeezed, one straight line from head to heels.",
    description: "Hold a straight-body position on your forearms and toes. Squeeze your glutes and brace your abs like you're about to take a light punch — that's what keeps the lower back from sagging into an arch. When the line breaks, the set is over, whatever the clock says.",
    avoidIf: [],
    icon: "🧘",
  },
  {
    id: "side-plank",
    name: "Side Plank",
    muscleGroup: "Core/Abs",
    secondaryMuscles: ["Shoulders", "Glutes"],
    equipment: "Bodyweight",
    difficulty: "Intermediate",
    cue: "Stacked feet, hips lifted high — don't let them sag toward the floor.",
    description: "Lie on your side, prop up on one forearm with your elbow under your shoulder, and lift your hips until your body forms a straight line. Targets the obliques and the deep side-stabilizers that regular planks miss. Drop the bottom knee to the floor for an easier version.",
    avoidIf: ["shoulder"],
    icon: "🧘",
  },
  {
    id: "crunch",
    name: "Crunch",
    muscleGroup: "Core/Abs",
    secondaryMuscles: [],
    equipment: "Bodyweight",
    difficulty: "Beginner",
    cue: "Curl your ribs toward your hips — shoulder blades off the floor is far enough.",
    description: "Lying on your back with knees bent, curl your upper spine forward until your shoulder blades leave the floor, then lower. It's a short, small movement — not a sit-up. Keep your chin off your chest and don't yank your head with your hands; fingertips behind the ears, elbows wide.",
    avoidIf: ["lower-back", "neck", "pregnancy"],
    icon: "🤸",
  },
  {
    id: "situp",
    name: "Sit-Up",
    muscleGroup: "Core/Abs",
    secondaryMuscles: [],
    equipment: "Bodyweight",
    difficulty: "Beginner",
    cue: "Roll up one vertebra at a time; exhale on the way up.",
    description: "From lying with knees bent, curl all the way up to sitting, then roll back down with control. The full range works the abs plus the hip flexors. Anchor-free is honest; hooking your feet lets the hip flexors take over. Repeated full spinal flexion is exactly what cranky lower backs dislike — the tag is earned.",
    avoidIf: ["lower-back", "neck", "pregnancy"],
    icon: "🤸",
  },
  {
    id: "dead-bug",
    name: "Dead Bug",
    muscleGroup: "Core/Abs",
    secondaryMuscles: [],
    equipment: "Bodyweight",
    difficulty: "Beginner",
    cue: "Lower back pressed flat while opposite arm and leg reach away.",
    description: "On your back with arms up and knees bent to 90°, slowly extend one arm overhead and the opposite leg out long, keeping your lower back glued to the floor, then switch sides. It looks easy and is quietly one of the best back-friendly core drills ever devised. If the lower back arches off the floor, shorten the reach.",
    avoidIf: ["pregnancy"],
    icon: "🪲",
  },
  {
    id: "bird-dog",
    name: "Bird Dog",
    muscleGroup: "Core/Abs",
    secondaryMuscles: ["Glutes", "Back"],
    equipment: "Bodyweight",
    difficulty: "Beginner",
    cue: "From all fours, reach opposite arm and leg long — a glass of water on your back shouldn't spill.",
    description: "On hands and knees, extend one arm and the opposite leg until both are level with your torso, pause, and return without letting your hips tip. A rehab-world classic for teaching the spine to stay still while the limbs move. Slow reps beat high reps; padding under the knees helps.",
    avoidIf: ["wrist", "knee"],
    icon: "🐕",
  },
  {
    id: "russian-twist",
    name: "Russian Twist",
    muscleGroup: "Core/Abs",
    secondaryMuscles: [],
    equipment: "Bodyweight",
    difficulty: "Intermediate",
    cue: "Lean back to 45°, rotate your chest side to side — the twist comes from the ribs, not the arms.",
    description: "Seated, lean back until your abs switch on, then rotate your torso side to side, touching the floor beside your hips (hold a dumbbell to progress). Lift the feet to make it harder. Rotate through the mid-back rather than whipping the arms across — and skip it entirely if twisting under load bothers your spine.",
    avoidIf: ["lower-back", "pregnancy"],
    icon: "🌀",
  },
  {
    id: "lying-leg-raise",
    name: "Lying Leg Raise",
    muscleGroup: "Core/Abs",
    secondaryMuscles: ["Quads"],
    equipment: "Bodyweight",
    difficulty: "Intermediate",
    cue: "Legs up to vertical, then lower them only as far as your lower back stays down.",
    description: "Lying flat, raise your legs to vertical and lower them toward the floor without letting your lower back peel off the ground. The lowering portion is the exercise. Hands under the hips help; bent knees make it easier. The moment your back arches, you've gone past your current range — stop higher.",
    avoidIf: ["lower-back", "pregnancy"],
    icon: "🦵",
  },
  {
    id: "hollow-hold",
    name: "Hollow Body Hold",
    muscleGroup: "Core/Abs",
    secondaryMuscles: [],
    equipment: "Bodyweight",
    difficulty: "Advanced",
    cue: "Press your lower back into the floor and hover shoulders and legs — banana shape.",
    description: "Lying on your back, press your lower back into the floor and lift your shoulders and straight legs a few inches, arms overhead, into a shallow banana shape. The gymnastics foundation position. Tuck the knees or raise the legs higher to scale it down — height is inversely proportional to difficulty.",
    avoidIf: ["lower-back", "neck", "pregnancy"],
    icon: "🍌",
  },
  {
    id: "pallof-press",
    name: "Band Pallof Press",
    muscleGroup: "Core/Abs",
    secondaryMuscles: ["Shoulders"],
    equipment: "Band",
    difficulty: "Intermediate",
    cue: "Press the band straight out from your chest and refuse to let it twist you.",
    description: "Anchor a band at chest height, stand side-on to it, and press the handle straight out from your sternum — the band tries to rotate you toward the anchor and your job is to not let it. Hold, return, switch sides. An anti-rotation gem that's gentle on almost everyone. Step further out for more fight.",
    avoidIf: [],
    icon: "🛡️",
  },

  // ─────────────────────────── GLUTES ───────────────────────────
  {
    id: "glute-bridge",
    name: "Glute Bridge",
    muscleGroup: "Glutes",
    secondaryMuscles: ["Hamstrings", "Core/Abs"],
    equipment: "Bodyweight",
    difficulty: "Beginner",
    cue: "Drive through your heels and squeeze your glutes to lift your hips — don't arch your back.",
    description: "Lying on your back with knees bent and feet flat, drive your hips up until your body is a straight line from knees to shoulders, pause with glutes squeezed hard, and lower. The lift should come from the glutes, not from arching the lower back — think 'tuck and lift', not 'arch and push'.",
    avoidIf: ["pregnancy"],
    icon: "🌉",
  },
  {
    id: "bb-hip-thrust",
    name: "Barbell Hip Thrust",
    muscleGroup: "Glutes",
    secondaryMuscles: ["Hamstrings", "Quads"],
    equipment: "Barbell",
    difficulty: "Intermediate",
    cue: "Shoulders on a bench, bar over your hips — drive up until your torso is level.",
    description: "With your upper back on a bench and a padded barbell across your hips, drive your hips up until your thighs and torso form a flat tabletop, chin tucked, then lower under control. The heaviest direct glute loading available. Full lockout with a hard squeeze beats extra plates with half range.",
    avoidIf: ["hip", "pregnancy"],
    icon: "🏋️",
  },
  {
    id: "donkey-kick",
    name: "Donkey Kick",
    muscleGroup: "Glutes",
    secondaryMuscles: ["Hamstrings", "Core/Abs"],
    equipment: "Bodyweight",
    difficulty: "Beginner",
    cue: "From all fours, press one flexed foot toward the ceiling, knee bent at 90°.",
    description: "On hands and knees, keep one knee bent at 90° and press that foot straight up toward the ceiling by squeezing the glute, then lower without touching the floor. The range is smaller than momentum wants it to be — stop where your back would start to arch. Pad the knees, keep the neck long.",
    avoidIf: ["wrist", "knee"],
    icon: "🐴",
  },
  {
    id: "fire-hydrant",
    name: "Fire Hydrant",
    muscleGroup: "Glutes",
    secondaryMuscles: ["Core/Abs"],
    equipment: "Bodyweight",
    difficulty: "Beginner",
    cue: "From all fours, lift one bent knee out to the side without tilting your hips.",
    description: "On hands and knees, lift one bent leg out to the side like the namesake dog, keeping both hips square to the floor, then lower. Works the side glutes that stabilize every step you take. Height doesn't matter; keeping the torso still does. Pairs naturally with donkey kicks.",
    avoidIf: ["wrist", "knee", "hip"],
    icon: "🚒",
  },
  {
    id: "clamshell",
    name: "Clamshell",
    muscleGroup: "Glutes",
    secondaryMuscles: [],
    equipment: "Bodyweight",
    difficulty: "Beginner",
    cue: "Lie on your side, knees bent, and open the top knee like a clamshell — feet stay together.",
    description: "Lying on your side with knees bent and stacked, keep your feet touching and lift the top knee open as far as you can without rolling your pelvis backward, then close slowly. A physical-therapy staple for the deep side glutes. Loop a mini-band above the knees when it gets easy.",
    avoidIf: [],
    icon: "🐚",
  },
  {
    id: "band-lateral-walk",
    name: "Banded Lateral Walk",
    muscleGroup: "Glutes",
    secondaryMuscles: ["Quads"],
    equipment: "Band",
    difficulty: "Beginner",
    cue: "Band above the knees, quarter squat, step sideways without letting the knees cave in.",
    description: "With a mini-band looped just above your knees, sit into a shallow squat and take deliberate sideways steps, keeping constant tension on the band and your knees pushed out. Ten steps one way, ten back. The burn in the side of your hips is the point — it's the muscles that keep knees tracking straight.",
    avoidIf: [],
    icon: "🦵",
  },
  {
    id: "cable-glute-kickback",
    name: "Cable Glute Kickback",
    muscleGroup: "Glutes",
    secondaryMuscles: ["Hamstrings"],
    equipment: "Cable",
    difficulty: "Intermediate",
    cue: "Ankle cuff on a low cable — sweep the leg straight back and squeeze.",
    description: "With an ankle strap on a low pulley, hinge slightly forward holding the machine, and sweep that leg straight back until the glute is fully contracted, then return under control. Kick back, not up — height past hip level just arches the lower back. Standing on one leg is part of the work.",
    avoidIf: ["balance"],
    icon: "🍑",
  },
  {
    id: "single-leg-glute-bridge",
    name: "Single-Leg Glute Bridge",
    muscleGroup: "Glutes",
    secondaryMuscles: ["Hamstrings", "Core/Abs"],
    equipment: "Bodyweight",
    difficulty: "Intermediate",
    cue: "One foot down, one leg extended — hips rise level, no tilting.",
    description: "A glute bridge performed on one leg with the other held straight or hugged to your chest. Doubles the load on the working glute and exposes left-right differences immediately. Keep the hips level as you rise; a tilting pelvis means the standing-side glute is being out-voted by the lower back.",
    avoidIf: ["pregnancy"],
    icon: "🌉",
  },

  // ─────────────────────────── QUADS ───────────────────────────
  {
    id: "bodyweight-squat",
    name: "Bodyweight Squat",
    muscleGroup: "Quads",
    secondaryMuscles: ["Glutes", "Hamstrings", "Core/Abs"],
    equipment: "Bodyweight",
    difficulty: "Beginner",
    cue: "Sit back and down between your hips, chest up, heels planted.",
    description: "Feet about shoulder width, toes slightly out, sit down between your hips as deep as comfortable and stand back up. Knees travel in line with the toes — forward past them is fine, caving inward is not. The single most useful movement pattern in the library; the depth that feels strong is your depth.",
    avoidIf: ["knee"],
    icon: "🦵",
  },
  {
    id: "goblet-squat",
    name: "Goblet Squat",
    muscleGroup: "Quads",
    secondaryMuscles: ["Glutes", "Core/Abs"],
    equipment: "Kettlebell",
    difficulty: "Beginner",
    cue: "Hug the weight at your chest — it counterbalances you into a taller, deeper squat.",
    description: "Hold a kettlebell or dumbbell in both hands against your chest and squat. The front-loaded weight acts as a counterbalance, which is why most people instantly squat deeper and more upright than without it. The thinking person's first loaded squat — and elbows-inside-knees at the bottom is a free mobility drill.",
    avoidIf: ["knee"],
    icon: "🦵",
  },
  {
    id: "bb-back-squat",
    name: "Barbell Back Squat",
    muscleGroup: "Quads",
    secondaryMuscles: ["Glutes", "Hamstrings", "Core/Abs"],
    equipment: "Barbell",
    difficulty: "Advanced",
    cue: "Bar on your upper back, big breath, brace, and stand the weight up out of the hole.",
    description: "The barbell across your upper traps, squat to at least parallel and drive back up. The king of leg exercises and also the one with the least tolerance for sloppy setup: brace hard before every rep, keep the whole foot planted, and use safety pins or a rack. Load only what your worst rep can handle.",
    avoidIf: ["knee", "lower-back", "hip"],
    icon: "🏋️",
  },
  {
    id: "forward-lunge",
    name: "Forward Lunge",
    muscleGroup: "Quads",
    secondaryMuscles: ["Glutes", "Hamstrings"],
    equipment: "Bodyweight",
    difficulty: "Beginner",
    cue: "Step forward, lower the back knee toward the floor, push back to standing.",
    description: "Step forward into a split stance and lower until both knees are near 90°, then push off the front foot to return. The front shin stays roughly vertical and the torso tall. The braking force of the forward step is what makes it harder on knees than its reverse cousin.",
    avoidIf: ["knee", "balance"],
    icon: "🦵",
  },
  {
    id: "reverse-lunge",
    name: "Reverse Lunge",
    muscleGroup: "Quads",
    secondaryMuscles: ["Glutes", "Hamstrings"],
    equipment: "Bodyweight",
    difficulty: "Beginner",
    cue: "Step backward into the lunge — easier on the knees than stepping forward.",
    description: "From standing, step one foot backward and lower the back knee toward the floor, then drive through the front heel to stand. Removing the forward braking step makes this the knee-friendlier lunge, and it's easier to balance too. Hold a wall or chair for confidence while learning.",
    avoidIf: ["knee", "balance"],
    icon: "🦵",
  },
  {
    id: "bulgarian-split-squat",
    name: "Bulgarian Split Squat",
    muscleGroup: "Quads",
    secondaryMuscles: ["Glutes", "Hamstrings", "Core/Abs"],
    equipment: "Dumbbell",
    difficulty: "Advanced",
    cue: "Rear foot on a bench, drop straight down — the front leg does all the work.",
    description: "A split squat with your rear foot elevated on a bench behind you, dumbbells at your sides. Universally feared and universally effective: it loads one leg at a time with none of the spinal load of a barbell squat. Find the foot spacing before adding weight, and expect the balance demand to be half the battle.",
    avoidIf: ["knee", "balance", "hip"],
    icon: "🦵",
  },
  {
    id: "leg-press",
    name: "Leg Press",
    muscleGroup: "Quads",
    secondaryMuscles: ["Glutes", "Hamstrings"],
    equipment: "Machine",
    difficulty: "Beginner",
    cue: "Lower the platform until your knees near 90° — never let your lower back curl off the pad.",
    description: "Seated in the machine, lower the platform with control and press it away without slamming into lockout. Heavy leg training without balancing a barbell. The cardinal sin is chasing depth until your pelvis rolls and lower back peels off the pad — stop above that point, every rep.",
    avoidIf: ["knee", "lower-back"],
    icon: "🦵",
  },
  {
    id: "leg-extension",
    name: "Leg Extension",
    muscleGroup: "Quads",
    secondaryMuscles: [],
    equipment: "Machine",
    difficulty: "Beginner",
    cue: "Straighten your knees fully, pause a beat at the top, lower slow.",
    description: "Seated in the machine with the pad on your shins, extend your knees until your legs are straight, squeeze, and lower with control. Pure isolated quad work with zero balance or back involvement. It concentrates force directly through the kneecap, which is exactly what some knees can't currently afford — hence the tag.",
    avoidIf: ["knee"],
    icon: "🦵",
  },
  {
    id: "wall-sit",
    name: "Wall Sit",
    muscleGroup: "Quads",
    secondaryMuscles: ["Glutes"],
    equipment: "Bodyweight",
    difficulty: "Beginner",
    cue: "Back flat on the wall, thighs parallel to the floor, and hold.",
    description: "Slide down a wall until your thighs are parallel with the floor, knees over ankles, and hold the invisible chair. An isometric quad burner with no movement to get wrong. Hands stay off the thighs — that's resting. Raise the seat height (shallower angle) to make it kinder to the knees.",
    avoidIf: ["knee"],
    icon: "🪑",
  },
  {
    id: "step-up",
    name: "Step-Up",
    muscleGroup: "Quads",
    secondaryMuscles: ["Glutes", "Calves"],
    equipment: "Bodyweight",
    difficulty: "Beginner",
    cue: "Whole foot on the box; drive through that heel without pushing off the floor leg.",
    description: "Step onto a sturdy box or bench, driving up through the leading leg until you're standing tall on it, then step down with control. The honest version barely pushes off the bottom foot. Start with a low step and raise it as strength and confidence grow — height changes everything.",
    avoidIf: ["knee", "balance"],
    icon: "🦵",
  },
  {
    id: "band-tke",
    name: "Band Terminal Knee Extension",
    muscleGroup: "Quads",
    secondaryMuscles: [],
    equipment: "Band",
    difficulty: "Beginner",
    cue: "Band behind the knee, anchored in front — straighten the knee against the pull.",
    description: "Loop a band around a post and behind one knee, step back for tension, and straighten that knee fully against the band's pull, squeezing the quad at lockout. A rehab-room favorite for waking up the muscle that stabilizes the kneecap, using a gentle range most knees tolerate well. As ever: your body has the final vote.",
    avoidIf: [],
    icon: "🦵",
  },

  // ───────────────────────── HAMSTRINGS ─────────────────────────
  {
    id: "db-rdl",
    name: "Dumbbell Romanian Deadlift",
    muscleGroup: "Hamstrings",
    secondaryMuscles: ["Glutes", "Back"],
    equipment: "Dumbbell",
    difficulty: "Intermediate",
    cue: "Push your hips straight back, soft knees, until the hamstrings pull the brakes.",
    description: "Holding dumbbells in front of your thighs, hinge by pushing your hips backward with a proud chest and slight knee bend, lowering the weights along your legs until your hamstrings hit their stretch limit, then stand by driving the hips forward. The hinge — not the squat — is the pattern. A rounding back is the signal to stop shallower.",
    avoidIf: ["lower-back"],
    icon: "🏋️",
  },
  {
    id: "bb-deadlift",
    name: "Barbell Deadlift",
    muscleGroup: "Hamstrings",
    secondaryMuscles: ["Glutes", "Back", "Core/Abs", "Quads"],
    equipment: "Barbell",
    difficulty: "Advanced",
    cue: "Bar over mid-foot, flat back, push the floor away and stand up tall.",
    description: "Pull a barbell from the floor to standing by bracing hard, wedging your hips, and driving through the whole foot. Nothing builds total-body strength like it, and nothing punishes a rounded back under fatigue like it either. Treat every rep like a max: same setup, same brace, and put the bar down before form frays.",
    avoidIf: ["lower-back", "hip"],
    icon: "🏋️",
  },
  {
    id: "leg-curl",
    name: "Lying Leg Curl",
    muscleGroup: "Hamstrings",
    secondaryMuscles: ["Calves"],
    equipment: "Machine",
    difficulty: "Beginner",
    cue: "Curl your heels to your glutes without your hips popping off the pad.",
    description: "Face-down on the machine with the pad at your ankles, curl your heels toward your glutes and lower slowly. Direct hamstring work with the spine fully supported, which makes it one of the most back-friendly leg exercises in the gym. If your hips lift as you curl, lighten the load.",
    avoidIf: [],
    icon: "🦵",
  },
  {
    id: "good-morning",
    name: "Good Morning",
    muscleGroup: "Hamstrings",
    secondaryMuscles: ["Glutes", "Back"],
    equipment: "Barbell",
    difficulty: "Advanced",
    cue: "Bar on your back, bow forward from the hips with a locked-flat spine.",
    description: "With a light barbell on your upper back, hinge forward until your torso approaches parallel, then stand by squeezing the hamstrings and glutes. Named for the bowing motion. The leverage is unforgiving — the bar sits far from your hips — so the loading stays humble and the back stays granite-flat, or you don't do it.",
    avoidIf: ["lower-back", "hip"],
    icon: "🌅",
  },
  {
    id: "single-leg-rdl",
    name: "Single-Leg Romanian Deadlift",
    muscleGroup: "Hamstrings",
    secondaryMuscles: ["Glutes", "Core/Abs"],
    equipment: "Dumbbell",
    difficulty: "Intermediate",
    cue: "Hinge on one leg, the other extending behind you as a counterweight.",
    description: "Balance on one leg and hinge forward, letting the free leg extend straight behind you until your body forms a T, then return. Hamstrings plus a serious balance challenge — hold a dumbbell in the opposite hand, or keep fingertips on a wall while learning. Square hips beat extra depth.",
    avoidIf: ["lower-back", "balance"],
    icon: "🦩",
  },
  {
    id: "nordic-curl",
    name: "Nordic Hamstring Curl",
    muscleGroup: "Hamstrings",
    secondaryMuscles: ["Glutes", "Core/Abs"],
    equipment: "Bodyweight",
    difficulty: "Advanced",
    cue: "Ankles anchored, kneel tall, and lower your body forward as slowly as possible.",
    description: "Kneel with your ankles anchored (partner, couch, loaded bar) and lower your straight body toward the floor using only your hamstrings as brakes, catching yourself with your hands. Even elite athletes fight for a few clean negatives. All the load runs through the knees against a pad, so they need to be happy about it.",
    avoidIf: ["knee"],
    icon: "🧎",
  },
  {
    id: "band-pull-through",
    name: "Band Pull-Through",
    muscleGroup: "Hamstrings",
    secondaryMuscles: ["Glutes"],
    equipment: "Band",
    difficulty: "Beginner",
    cue: "Face away from the anchor, band between your legs — hinge back, then snap hips forward.",
    description: "Anchor a band low behind you, hold it between your legs facing away, hinge your hips back until you feel the hamstring stretch, then stand by driving the hips through and squeezing the glutes. Teaches the hip hinge with the resistance pulling you into the exact right direction. Friendly to nearly every body.",
    avoidIf: [],
    icon: "🍑",
  },

  // ─────────────────────────── CALVES ───────────────────────────
  {
    id: "standing-calf-raise",
    name: "Standing Calf Raise",
    muscleGroup: "Calves",
    secondaryMuscles: [],
    equipment: "Bodyweight",
    difficulty: "Beginner",
    cue: "Rise to your tiptoes, pause at the top, lower until you feel a heel stretch.",
    description: "Stand tall (fingertips on a wall for balance), rise as high as you can onto the balls of your feet, pause, and lower until your heels feel a gentle stretch — a step edge gives extra range. Calves respond to full range and patience, not bouncing. Slow down before you add weight.",
    avoidIf: [],
    icon: "🦶",
  },
  {
    id: "single-leg-calf-raise",
    name: "Single-Leg Calf Raise",
    muscleGroup: "Calves",
    secondaryMuscles: [],
    equipment: "Bodyweight",
    difficulty: "Intermediate",
    cue: "All your weight on one foot — full rise, full stretch, no bouncing.",
    description: "A calf raise on one leg, doubling the load and exposing exactly how much stronger one side is. Hold a wall or rail with one hand; the free hand can hold a dumbbell once fifteen smooth reps feel easy. The single-leg stance is itself a balance drill, hence the tag.",
    avoidIf: ["balance"],
    icon: "🦶",
  },
  {
    id: "seated-calf-raise",
    name: "Seated Calf Raise",
    muscleGroup: "Calves",
    secondaryMuscles: [],
    equipment: "Machine",
    difficulty: "Beginner",
    cue: "Knees bent under the pad — press up through the balls of your feet.",
    description: "Seated with the pad on your knees, raise your heels as high as possible and lower into a full stretch. The bent knee shifts the work to the soleus, the deep calf muscle a standing raise mostly misses — which is why both versions exist. No machine? Sit with dumbbells on your knees.",
    avoidIf: [],
    icon: "🦶",
  },
  {
    id: "calf-press-leg-press",
    name: "Calf Press on Leg Press",
    muscleGroup: "Calves",
    secondaryMuscles: [],
    equipment: "Machine",
    difficulty: "Beginner",
    cue: "Balls of your feet on the platform's edge; press through full ankle range.",
    description: "In the leg press machine with only the balls of your feet on the bottom edge of the platform, press the sled through a full ankle range — deep stretch to full point. Lets you load the calves heavily with zero balance demand. Keep a slight knee bend and control the stretch; don't let the sled yank your heels down.",
    avoidIf: [],
    icon: "🦶",
  },
  {
    id: "toe-walk",
    name: "Toe Walks",
    muscleGroup: "Calves",
    secondaryMuscles: ["Core/Abs"],
    equipment: "Bodyweight",
    difficulty: "Beginner",
    cue: "Walk on your tiptoes, tall as possible, heels never touching down.",
    description: "Rise onto the balls of your feet and simply walk, staying as tall as you can for 20–30 meters or a slow lap of the room. Ankle strength, calf endurance, and a little balance practice disguised as a silly walk. Do it barefoot when possible; near a wall or counter if wobbling is a concern.",
    avoidIf: ["balance"],
    icon: "🩰",
  },
  {
    id: "db-calf-raise",
    name: "Dumbbell Calf Raise",
    muscleGroup: "Calves",
    secondaryMuscles: [],
    equipment: "Dumbbell",
    difficulty: "Beginner",
    cue: "Dumbbell in one hand, other hand on the wall — raise, pause, stretch.",
    description: "A standing calf raise holding a dumbbell in one hand while the other hand steadies you against a wall. The simplest way to load calves at home. Do all reps holding the weight on one side, then swap — the off-hand support means balance never limits the set.",
    avoidIf: [],
    icon: "🦶",
  },

  // ───────────────────── FULL BODY/CARDIO ─────────────────────
  {
    id: "burpee",
    name: "Burpee",
    muscleGroup: "Full Body/Cardio",
    secondaryMuscles: ["Chest", "Quads", "Core/Abs"],
    equipment: "Bodyweight",
    difficulty: "Advanced",
    cue: "Squat, kick back to a plank, push-up, jump feet in, leap — repeat.",
    description: "Drop your hands to the floor, kick back into a plank (optionally with a push-up), hop your feet back in, and jump straight up. The whole gym in one movement and brutally effective conditioning — also a lot of impact through wrists and knees at speed. Step the feet in and skip the jump for a gentler version.",
    avoidIf: ["knee", "high-impact", "wrist", "pregnancy"],
    icon: "🔥",
  },
  {
    id: "jump-squat",
    name: "Jump Squat",
    muscleGroup: "Full Body/Cardio",
    secondaryMuscles: ["Quads", "Glutes", "Calves"],
    equipment: "Bodyweight",
    difficulty: "Advanced",
    cue: "Squat down, explode up, and land soft like landing on eggshells.",
    description: "A bodyweight squat that finishes with a jump, landing softly back into the next rep. Builds explosive power and spikes the heart rate in seconds. The landing is the skill: quiet feet, bent knees, hips back. If landings are loud or joints complain, regular squats deliver most of the benefit.",
    avoidIf: ["knee", "high-impact", "pregnancy"],
    icon: "🦘",
  },
  {
    id: "jumping-jack",
    name: "Jumping Jacks",
    muscleGroup: "Full Body/Cardio",
    secondaryMuscles: ["Shoulders", "Calves"],
    equipment: "Bodyweight",
    difficulty: "Beginner",
    cue: "Jump feet wide as arms swing overhead, then snap back together.",
    description: "The playground classic: jump your feet out wide while your arms swing overhead, then jump back to standing. A friendly whole-body warm-up that gets blood moving fast. For a no-impact version, step one foot out at a time while the arms do the same swing — same rhythm, no jumping.",
    avoidIf: ["knee", "high-impact"],
    icon: "⭐",
  },
  {
    id: "high-knees",
    name: "High Knees",
    muscleGroup: "Full Body/Cardio",
    secondaryMuscles: ["Quads", "Calves", "Core/Abs"],
    equipment: "Bodyweight",
    difficulty: "Intermediate",
    cue: "Run in place, driving knees to hip height, quick light feet.",
    description: "Sprint in place, driving each knee up toward hip height with fast, light ground contacts and pumping arms. As intense as you make it — twenty seconds honest effort is a legitimate conditioning interval. It's repeated impact and deep hip flexion, so the tags do a lot of work here; marching is the calm alternative.",
    avoidIf: ["knee", "high-impact", "hip"],
    icon: "🏃",
  },
  {
    id: "shadow-boxing",
    name: "Shadow Boxing",
    muscleGroup: "Full Body/Cardio",
    secondaryMuscles: ["Shoulders", "Core/Abs"],
    equipment: "Bodyweight",
    difficulty: "Beginner",
    cue: "Light on your feet, snappy punches at an imaginary target — never full lockout.",
    description: "Bounce lightly on your feet and throw combinations — jabs, crosses, hooks — at the air, rotating through the hips with each punch. Cardio, coordination, and stress relief with zero equipment. Keep a slight bend at the end of every punch; snapping the elbow to full extension repeatedly is what makes shoulders and elbows grumpy.",
    avoidIf: ["shoulder"],
    icon: "🥊",
  },
  {
    id: "mountain-climber",
    name: "Mountain Climbers",
    muscleGroup: "Full Body/Cardio",
    secondaryMuscles: ["Core/Abs", "Shoulders", "Quads"],
    equipment: "Bodyweight",
    difficulty: "Intermediate",
    cue: "From a plank, drive knees toward your chest in a fast alternating rhythm.",
    description: "In a high plank, run your knees toward your chest one at a time while your shoulders stay stacked over your wrists and your hips stay low. A core exercise wearing a cardio costume. Slow it down to a deliberate march to drop the impact and keep the core work; the fast version is what earns the tags.",
    avoidIf: ["wrist", "knee", "high-impact"],
    icon: "⛰️",
  },
  {
    id: "kb-swing",
    name: "Kettlebell Swing",
    muscleGroup: "Full Body/Cardio",
    secondaryMuscles: ["Glutes", "Hamstrings", "Back", "Core/Abs"],
    equipment: "Kettlebell",
    difficulty: "Intermediate",
    cue: "It's a hip snap, not an arm lift — the bell floats to chest height.",
    description: "Hinge and hike the kettlebell back between your legs, then snap your hips forward so the bell floats up to chest height, arms relaxed like ropes. Cardio and posterior-chain power in one package. Every swing is a rep of the hip hinge — done with a rounded back it becomes a lower-back grievance generator, hence the tag.",
    avoidIf: ["lower-back"],
    icon: "🏋️",
  },
  {
    id: "bear-crawl",
    name: "Bear Crawl",
    muscleGroup: "Full Body/Cardio",
    secondaryMuscles: ["Core/Abs", "Shoulders", "Quads"],
    equipment: "Bodyweight",
    difficulty: "Intermediate",
    cue: "Hands and feet down, knees hovering an inch off the floor — crawl slow and level.",
    description: "On hands and feet with knees bent and hovering just off the ground, crawl forward moving opposite hand and foot together, keeping your back flat enough to balance a cup of coffee. Surprisingly humbling core and shoulder work. Crawl backward for a bonus challenge; speed is not the goal, stillness of the torso is.",
    avoidIf: ["wrist"],
    icon: "🐻",
  },
  {
    id: "march-in-place",
    name: "March in Place",
    muscleGroup: "Full Body/Cardio",
    secondaryMuscles: ["Quads", "Calves"],
    equipment: "Bodyweight",
    difficulty: "Beginner",
    cue: "Lift knees to a comfortable height with a steady rhythm and swinging arms.",
    description: "March on the spot, lifting the knees to a comfortable height and swinging the arms naturally. The gentlest conditioning option in the deck — genuinely useful as a warm-up, a between-sets breather, or the low-impact stand-in for anything tagged with jumping. Untagged on purpose: nearly every body tolerates it.",
    avoidIf: [],
    icon: "🚶",
  },
  {
    id: "db-thruster",
    name: "Dumbbell Thruster",
    muscleGroup: "Full Body/Cardio",
    secondaryMuscles: ["Quads", "Glutes", "Shoulders", "Triceps"],
    equipment: "Dumbbell",
    difficulty: "Advanced",
    cue: "Front squat straight into an overhead press — one fluid motion.",
    description: "Hold dumbbells at your shoulders, squat, and use the momentum of standing to drive the weights overhead in one continuous movement, then bring them down into the next squat. A squat, a press, and a cardio interval had a baby. The overhead finish and deep squat mean three sets of joints all need to sign off on it.",
    avoidIf: ["shoulder", "knee", "lower-back"],
    icon: "🚀",
  },
  {
    id: "farmers-carry",
    name: "Farmer's Carry",
    muscleGroup: "Full Body/Cardio",
    secondaryMuscles: ["Core/Abs", "Back", "Shoulders"],
    equipment: "Kettlebell",
    difficulty: "Beginner",
    cue: "Heavy weight in each hand, stand tall, and just walk.",
    description: "Pick up a heavy kettlebell or dumbbell in each hand and walk with tall posture, level shoulders, and unhurried steps for distance or time. Grip, core, posture, and conditioning from the most functional movement there is: carrying heavy things. Almost impossible to do wrong — if you can't stay tall, the weights are too heavy.",
    avoidIf: [],
    icon: "🧳",
  },
  {
    id: "row-machine",
    name: "Rowing Machine",
    muscleGroup: "Full Body/Cardio",
    secondaryMuscles: ["Back", "Quads", "Core/Abs"],
    equipment: "Machine",
    difficulty: "Beginner",
    cue: "Legs push, body swings back, arms pull — then reverse it, in that order.",
    description: "Low-impact full-body cardio on the erg. The stroke sequence is legs-body-arms on the drive, arms-body-legs on the recovery; most beginners yank with the arms first and row hunched. Damper at 3–5, long smooth strokes. Rounding the lower back at the catch is the habit the tag exists to flag.",
    avoidIf: ["lower-back"],
    icon: "🚣",
  },
];

// Node export for validate.js; browsers just use the top-level consts.
if (typeof module !== "undefined" && module.exports) {
  module.exports = { MUSCLE_GROUPS, CONDITIONS, EXERCISES };
}
